### PR TITLE
Add all function and value slots to Closure_approximation

### PR DESCRIPTION
**Pull request by mshinwell**
At present no value slots are exported in classic mode closure approximations.  This can cause failures when inlining a function generated in classic mode into a file being compiled with Simplify.  When any `Project_value_slot` operations are found operating on the closure of the function being inlined, the types will show exactly no value slots are present, causing `Invalid`.  This PR aims to fix that by propagating the set of value slots.

### CODE REVIEW

**Comment by lthls** [comment]
Now that I think about it, I should probably have used some constructor other than `MTG.exactly_this_closure` to construct the types. What we know is more like "at least this function slot".
Have you tested this patch with mutually recursive functions using `Project_function_slot` ?

**Comment by mshinwell** [comment]
I've updated this to remember all function slots too.

**Comment by mshinwell** [comment]
Here is a potential test:
```
% cat fs.ml
let r = Random.int 42

let[@inline available] rec f x =
  if x < 0 then g x else (r, f, g)

and[@inline available] g y =
  if y < 0 then f y else (r, f, g)

% cat fsu.ml
let f x =
  (Fs.f [@inlined]) x, (Fs.g [@inlined]) x

% ./_install/bin/ocamlopt -Oclassic -rectypes -c fs.ml
% ./_install/bin/ocamlopt -O2 -dflambda -color always -rectypes -c fsu.ml
```
For `fs.cmx` we get type equations as follows (as seen in `ocamlobjinfo`):
```
 (type_equations
  {(Fs.camlFs
    (Val
     (Variant
      (blocks
       ((alloc_mode Heap) (known
         {(tag_0 => (Known 3),
           ((kind 𝕍) (Val ⊤)
            (Val
             ((alloc_mode Heap_or_local) (known
               {((f/0 ∷ 𝕍)
                 => (Known ((closures { (f/0 ∷ 𝕍) (g/1 ∷ 𝕍) })
                            (value_slots { (r/0 ∷ 𝕍=tagged_ℕ𝕚) }))),
                 ((function_types
                   {((f/0 ∷ 𝕍)
                     (Ok (function_type (code_id camlFs__f_0_0_code)
                          (rec_info (Rec_info 0))))) ((g/1 ∷ 𝕍) Unknown)})
                  (closure_types
                   ((function_slot_components_by_index
                     {((f/0 ∷ 𝕍) (Val ⊤)) ((g/1 ∷ 𝕍) (Val ⊤))})))
                  (value_slot_types
                   ((value_slot_components_by_index
                     {((r/0 ∷ 𝕍=tagged_ℕ𝕚) (Val ⊤))})))))}) (other Bottom)))
            (Val
             ((alloc_mode Heap_or_local) (known
               {((g/1 ∷ 𝕍)
                 => (Known ((closures { (f/0 ∷ 𝕍) (g/1 ∷ 𝕍) })
                            (value_slots { (r/0 ∷ 𝕍=tagged_ℕ𝕚) }))),
                 ((function_types
                   {((f/0 ∷ 𝕍) Unknown)
                    ((g/1 ∷ 𝕍)
                     (Ok (function_type (code_id camlFs__g_1_1_code)
                          (rec_info (Rec_info 0)))))})
                  (closure_types
                   ((function_slot_components_by_index
                     {((f/0 ∷ 𝕍) (Val ⊤)) ((g/1 ∷ 𝕍) (Val ⊤))})))
                  (value_slot_types
                   ((value_slot_components_by_index
                     {((r/0 ∷ 𝕍=tagged_ℕ𝕚) (Val ⊤))})))))}) (other Bottom)))))})
        (other Bottom))) (tagged_imms (Naked_immediate ⊥)))))})
```

**Comment by mshinwell** [comment]
The result of compiling `fsu.ml` is:
```
   (λ〈k13〉《k12》⟅my_region/23⟆ (x/25 ∷ 𝕍=tagged_ℕ𝕚) (my_closure/24 ∷ 𝕍) my_depth/22 .
    (Pfield/27 = (((Block_load (Values (tag ⊤) (size ⊤) (field_kind Any_value)) Immutable) Fs.camlFs 2) fsu.ml:2,23--40)
     r/36 = (((Project_value_slot ((Fs.g/1 ∷ 𝕍) (Fs.r/0 ∷ 𝕍=tagged_ℕ𝕚) 𝕍=tagged_ℕ𝕚)) Pfield/27) fsu.ml:2,23--42)
     f/37 = (((Project_function_slot ((Fs.g/1 ∷ 𝕍) → (Fs.f/0 ∷ 𝕍))) Pfield/27) fsu.ml:2,23--42)
     prim/38 = ((< x/25 0) fsu.ml:2,23--42;fs.ml:7,5--10)
     Pintcomp/39 = ((Tag_imm prim/38) fsu.ml:2,23--42;fs.ml:7,5--10)
     ((switch prim/38
      | 0 ↦ apply_cont k19 Pintcomp/39
      | 1 ↦ apply_cont k20 Pintcomp/39)
      k20 (Pintcomp/39 ∷ 𝕍) #One:
      ((apply
        (((coerce f/37 (depth 0 -> 1))〈k26〉《k12》⟅my_region/23⟆ (x/25)) 
         (args_arity 𝕍=tagged_ℕ𝕚) (return_arity 𝕍=Variant((consts ({ })) (non_consts ({(0 [=tagged_ℕ𝕚 * *])})))) 
         (call_kind (Function (function_call Indirect_known_arity) (alloc_mode Heap))) 
         (dbg fsu.ml:2,23--42;fs.ml:7,16--19) (inline Default_inlined) 
         (inlining_state (depth 1, arguments Oclassic)) (probe_name ()) 
         (position Normal)))
       k26 (param/83 ∷ 𝕍=Variant((consts ({ })) (non_consts ({(0 [=tagged_ℕ𝕚 * *])})))) #One: apply_cont k16 param/83 Pintcomp/39)
      k19 (Pintcomp/39 ∷ 𝕍) #One:
      Pmakeblock/43 = (((Make_block (Values (tag 0) (shape (𝕍=tagged_ℕ𝕚 𝕍 𝕍))) Immutable Heap) r/36 (coerce f/37 (depth 0 -> 1)) (coerce Pfield/27 (depth 0 -> 1))) fsu.ml:2,23--42;fs.ml:7,25--34)
      apply_cont k16 Pmakeblock/43 Pintcomp/39 fsu.ml:2,23--42;fs.ml:7,25--34)
     k16 (apply_result/26 ∷ 𝕍=Variant((consts ({ })) (non_consts ({(0 [=tagged_ℕ𝕚 * *])})))) (Pintcomp/39 ∷ 𝕍) #More_than_one:
     cse_param/45 = Pintcomp/39
     (Pfield/56 = (((Block_load (Values (tag ⊤) (size ⊤) (field_kind Any_value)) Immutable) Fs.camlFs 1) fsu.ml:2,2--19)
      r/65 = (((Project_value_slot ((Fs.f/0 ∷ 𝕍) (Fs.r/0 ∷ 𝕍=tagged_ℕ𝕚) 𝕍=tagged_ℕ𝕚)) Pfield/56) fsu.ml:2,2--21)
      g/66 = (((Project_function_slot ((Fs.f/0 ∷ 𝕍) → (Fs.g/1 ∷ 𝕍))) Pfield/56) fsu.ml:2,2--21)
      (untagged/69 = ((Untag_imm cse_param/45) fsu.ml:2,2--21)
       (switch untagged/69
       | 0 ↦ goto k24
       | 1 ↦ goto k25)
       k25 #One:
       (apply
        (((coerce g/66 (depth 0 -> 1))〈k21〉《k12》⟅my_region/23⟆ (x/25)) 
         (args_arity 𝕍=tagged_ℕ𝕚) (return_arity 𝕍=Variant((consts ({ })) (non_consts ({(0 [=tagged_ℕ𝕚 * *])})))) 
         (call_kind (Function (function_call Indirect_known_arity) (alloc_mode Heap))) 
         (dbg fsu.ml:2,2--21;fs.ml:4,16--19) (inline Default_inlined) 
         (inlining_state (depth 1, arguments Oclassic)) (probe_name ()) 
         (position Normal)))
       k24 #One:
       Pmakeblock/72 = (((Make_block (Values (tag 0) (shape (𝕍=tagged_ℕ𝕚 𝕍 𝕍))) Immutable Heap) r/65 (coerce Pfield/56 (depth 0 -> 1)) (coerce g/66 (depth 0 -> 1))) fsu.ml:2,2--21;fs.ml:4,25--34)
       apply_cont k21 Pmakeblock/72 fsu.ml:2,2--21;fs.ml:4,25--34)
      k21 (apply_result/55 ∷ 𝕍=Variant((consts ({ })) (non_consts ({(0 [=tagged_ℕ𝕚 * *])})))) #More_than_one:
      Pmakeblock/82 =
       (((Make_block (Values (tag 0) (shape (𝕍=Variant((consts ({ })) (non_consts ({(0 [=tagged_ℕ𝕚 * *])}))) 𝕍=Variant((consts ({ })) (non_consts ({(0 [=tagged_ℕ𝕚 * *])})))))) Immutable Heap)
         apply_result/55 apply_result/26) fsu.ml:2,2--42)
      return k13 Pmakeblock/82 fsu.ml:2,2--42)))))
```

**Comment by mshinwell** [comment]
I also compiled a modified version of this test into an executable to check the recursion between the functions is ok, and it runs fine:
```
% cat fs.ml
let r = Random.int 42

let[@inline available] rec f x =
  Printf.printf "f\n%!";
  if x < 0 then g x else (r, f, g)

and[@inline available] g y =
  Printf.printf "g\n%!";
  if y < 0 then f (y + 1) else (r, f, g)

% cat fsu.ml
let f x =
  (Fs.f [@inlined]) x, (Fs.g [@inlined]) x

let _ = Sys.opaque_identity (f (-42))
```

**Comment by lthls** [comment]
I think the code is correct, but I think we could have a much smaller patch by introducing a function `closure_with_at_least_this_function` in `More_type_creators` and using that in `Typing_env.Serializable.create_from_closure_conversion_approx` instead of `exactly_this_closure`.

**Pull request merged**
