### PR TITLE
Promote float32 to stable

### PR DESCRIPTION
**Pull request by TheNumbat**
Adds a maturity level to the `small_numbers` extension. The float32 features are enabled at the stable maturity, which is the default. In the future, we can add small ints at the beta maturity.

The float32 libraries have been moved from `Stdlib_beta` to `Stdlib_stable`. This required adjusting the tests a bit (and also deletes a redundant test file, not sure how that got merged).

### CODE REVIEW

**Review by dkalinichenko-js — APPROVED** [review]
LGTM

**Comment by ccasin** [comment]
@mshinwell yes

**Comment by ccasin** [comment]
Actually, apparently not - @ncik-roberts found a bug in statically allocated closures containing a float32#, so let's wait to merge this until that is fixed.

**Comment by TheNumbat** [comment]
Yeah, will merge following #2698

**Pull request merged**
