### PR TITLE
Vectorizer: check register compatibility

### PR DESCRIPTION
**Pull request by gretay-js**
When joining vectorized computations, check that registers used as address arguments in one computation are not vectorized in the other comptutation.

### CODE REVIEW

**Comment by xclerc** [comment]
It looks correct, but would it be easy to add a test
showing how main is currently inadequate?

**Comment by gretay-js** [comment]
> It looks correct, but would it be easy to add a test showing how main is currently inadequate?

I tried to minimize the example, but it's a bit hard to reproduce as it involves first class modules inlining and ppx.

**Review by xclerc — APPROVED** [review]
OK, let's merge it as-is then.

**Comment by xclerc** [comment]
(Just for the record: the way the issue was
spotted was a rejection by the register
allocation validator.)

**Pull request merged**
