### PR TITLE
Make matches exhaustive (amd64)

### PR DESCRIPTION
**Pull request by gretay-js**
Suggested in https://github.com/ocaml-flambda/flambda-backend/pull/44#discussion_r646582506

### CODE REVIEW

**Comment by mshinwell** [comment]
This is a good idea, but if we're going to do it, let's enable warning 4 on these files?  You should be able to add `[@@@ocaml.warning "+4"]` at the top of them.

**Comment by xclerc** [comment]
(Assuming all the intrinsics will end up under `Ispecific`, it might be
enough to be exhaustive only for this constructor.)

**Comment by mshinwell** [comment]
I think it would be a good change to move to exhaustive matches as much as possible, just due to the number of bugs caught by them...

**Comment by xclerc** [comment]
I agree; I just felt bad for suggesting something so verbose.

**Comment by gretay-js** [comment]
I've enabled warning 4 wherever possible. The only missing files are emit.mlp and selection.ml.
I also fixed some formatting problems.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
