### PR TITLE
Ports #1420 (local immutable array)

### PR DESCRIPTION
**Pull request by riaqn**
This trivially ports the runtime part of #1420. Note that some changes are already introduced by previous porting PRs.

### CODE REVIEW

**Comment by stedolan** [comment]
There are some tests for this - do they pass now?

**Comment by riaqn** [comment]
Sorry I should mention - yes all tests under `lib-array` and `typing-local` passed.

**Comment by stedolan** [comment]
The patch here looks good, but there are a couple of `CR ocaml 5 runtime` at the bottom of `array.c` that should be looked at as well. (I'm not sure whether there are tests for those)

**Comment by riaqn** [comment]
Those `CR ocaml 5 runtime` are taken care of.

**Review by TheNumbat — APPROVED** [review]

**Pull request merged**
