### PR TITLE
`tast_{iterator,mapper}` were missing locs in jkind annotations

### PR DESCRIPTION
**Pull request by ccasin**
This fixes a small bug in the ocaml 5 merge that I noticed while doing the merlin merge.

Review: @ncik-roberts ?

### CODE REVIEW

**Review by ncik-roberts — APPROVED** [review]
Good catch.

**Comment by ncik-roberts** [comment]
Though it will now need to map over the second component of the tuple in light of #1907.

**Comment by ccasin** [comment]
> Though it will now need to map over the second component of the tuple in light of #1907.

Oops!  (Somehow I was testing a different branch than I was working on.)

Perhaps take a quick second look, as the type of the iterator also had to change.

**Review by ncik-roberts — APPROVED** [review]
Seems like a good approach to me.

**Pull request merged**
