### PR TITLE
Tidy-ups in Simplify_set_of_closures

### PR DESCRIPTION
**Pull request by mshinwell**
Split out two pieces of deeply-nested code into new functions `simplify_function_body` and `compute_result_types`.  Added a record type to remove the large tuple, which had the potential for confusion as multiple elements had the same type.

Includes #885.

### CODE REVIEW

**Comment by mshinwell** [comment]
Plus tidy-ups in the lifting decision code to reduce deep nesting.

**Comment by mshinwell** [comment]
A couple more things now: the context module for `Simplify_set_of_closures` now lives in its own file, which reduces a long indented section.  I've also tidied up `dacc_for_function`.  The main `Simplify_set_of_closures` file is 900 lines now which is rather easier to navigate.

**Review by lthls — APPROVED** [review]
I haven't reviewed the commit that creates `Set_of_closures_context`, as it's not convenient with the Github interface, but assuming it's only moving code around the PR is fine.

**Comment by mshinwell** [comment]
Yes that's right.

**Pull request merged**
