### PR TITLE
Pun labelled arguments with type constraint in function applications

### PR DESCRIPTION
**Pull request by gretay-js**
Backport https://github.com/ocaml/ocaml/pull/10434

### CODE REVIEW

**Comment by lpw25** [comment]
Looks like you've got a rouge commit in there.

**Comment by lpw25** [comment]
For changes like this, which are entirely to the front-end, what is our process? Should these go to a stand-alone ocaml repo first? @mshinwell ?

**Comment by gretay-js** [comment]
> Looks like you've got a rogue commit in there.

fixed, thanks! (it was needed to build without warnings, but has since been merged in.)

**Comment by mshinwell** [comment]
Just squash and merge as normal.  In due course I'm going to set up another upstream-like repo which contains all of these changes, so they will get moved across then, and the subtree updated to be based on that repo (rather than upstream as at present).  I'm also planning to add some better labelling to PRs so we know how they should be treated.

**Pull request merged**
