### PR TITLE
File magic updates

### PR DESCRIPTION
**Pull request by gretay-js**
Follow up on a discussion in #275. 
Tested by copying the content of both "magic" files to `~/.magic`, and running on some compilation artifacts from opam and flambda-backend.

### CODE REVIEW

**Comment by mshinwell** [comment]
@gretay-js is this still ready to go?

**Comment by gretay-js** [comment]
> @gretay-js is this still ready to go?

no, we changed the naming scheme, I'll update it.

**Comment by mshinwell** [comment]
@gretay-js Is this PR still required?

**Comment by gretay-js** [comment]
> @gretay-js Is this PR still required?

it has never been strictly required, it just adds missing file types.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
