### PR TITLE
Restore #1455: Communicate layouts to middle end

### PR DESCRIPTION
**Pull request by goldfirere**
This restores #1455. The first commit is just #1455; later commits fix the bug in `type_sort_exn` by removing `type_sort_exn`.

I will not be around to shepherd this one through, so I nominate @ccasin.

I am setting this up with the nightly test infrastructure for thorough testing.

### CODE REVIEW

**Comment by goldfirere** [comment]
This will require a few new dependencies added to our build files. I've pushed some to the branch used for nightly testing. But there are probably more -- my attempt to build the whole codebase failed with an out-of-memory error. I think that, until we can have transitive dependencies, these additions are unavoidable.

**Comment by ccasin** [comment]
The nightly testing wasn't working because we were out of sync with the main branch, so I've rebased this onto the latest ocaml, force pushed to here and #1512, and locked the testing feature for rebase.  I'll try to review this later today.

**Review by ccasin — APPROVED** [review]
I have reviewed the new commits and they look good - probably an overall improvement even ignoring the missing cmi errors, anyway.  Thanks for dealing with this.

I am a tiny bit sad that some of the errors point at a whole function instead of the problematic bit, but I don't see a quick fix and anyway our goal is to eliminate missing cmis soon, making these errors unreachable.

I'm still working on getting this through the nightly build - which is unfortunately failing for other reasons - but it should be good to merge, any failures caused by this will be very easy to fix by following the hint.

**Comment by ccasin** [comment]
I believe this will need approval from @mshinwell and one of @gretay-js or @xclerc .

This is just a copy of #1455, which was rolled back, with a type system improvement to address the reason it was rolled back.  No changes in the parts you approve for.

**Review by gretay-js — APPROVED** [review]
For files in `backend` and `ocaml/asmcomp` only.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
