### PR TITLE
Memoization for typeopt

### PR DESCRIPTION
**Pull request by chambart**
This is an experiment to try to reduce the cost of `Typeopt.layout`

### CODE REVIEW

**Comment by ccasin** [comment]
I'm not really sure gadts are the only problem, but if they are, you could try checking for the presence of gadt equations in the environment with `Env.has_local_constraints` and not using the cache in that case.  This should still get you most of the performance savings.

**Comment by Ekdohibs** [comment]
I tried to investigate the problem, and it looks like there is an `Invalid` produced inside `typing/env.ml`. Here is a minimized example :
```
type module_data =
  { mda_declaration : unit }

and module_entry =
  | Mod_local of module_data
  | Mod_persistent

let[@inline never] find_pers_mod name : module_data = assert false

type _ load =
  | Load : module_data load
  | Don't_load : unit load


let lookup_ident_module (type a) (load : a load) data name =
  match data with
  | Mod_local mda -> assert false
  | Mod_persistent -> begin
      match load with
      | Don't_load ->
          0, (() : a)
      | Load -> begin
          let mda = find_pers_mod name in
          0, (mda : a)
        end
    end
```

**Comment by chambart** [comment]
Thanks @ccasin I will try that. This, should be ok now hopefully.
And thanks @Ekdohibs for the minimisation (it does work now)

**Comment by chambart** [comment]
Ok, so now the failures are 'expected': The type information is more precise because the memoization is ok with reusing more precise type information.
I will just promote the new results

**Comment by Ekdohibs** [comment]
I'm slightly worried about reusing more precise type information: this could cause produced types to get extremely large (as is seen on some of the tests). I'm not sure whether it could have a performance impact further on or not, this might need testing.
Moreover, since there are two independent axes for "more precise", if we alternate querying with more precise information on one axis but less precise on the other, the memoizations erase each other (of course, this is still better than the current status).

**Comment by mshinwell** [comment]
Closing for now, but we will come back to this in due course.

**Pull request closed without merging**
