### PR TITLE
Update opam testing instructions in HACKING.md

### PR DESCRIPTION
**Pull request by lthls**
Cc @lukemaurer, in case you're interested in testing the new instructions.

### CODE REVIEW

**Comment by mshinwell** [comment]
@lukemaurer please approve

**Review by lukemaurer — APPROVED** [review]
Tested and it works. It might be worth emphasizing that you have to have your stock 4.12.0 switch active in your shell (that is, run `eval $(opam env)`) _before_ creating the new switch. It might be possible to disentangle things if you run `eval $(opam env)` afterward with the right options but it's easiest just to avoid the situation.

**Comment by lthls** [comment]
> Tested and it works. It might be worth emphasizing that you have to have your stock 4.12.0 switch active in your shell (that is, run `eval $(opam env)`) _before_ creating the new switch. It might be possible to disentangle things if you run `eval $(opam env)` afterward with the right options but it's easiest just to avoid the situation.

I don't think it's supposed to be the case. The new `install_for_opam` rule was introduced specifically for that: you need the stock 4.12.0 switch for compiling flambda-backend, but none of the opam commands should need it.

**Comment by lthls** [comment]
In particular, I usually run the `opam custom-install` command in a different directory:
```
cd ~/opam_tests
opam switch create . --empty
opam custom-install ocaml-variants.4.12.0+flambda2 -- make -C path_to_flambda2/ install_for_opam
opam reinstall --forget-pending
opam install ocaml.4.12.0
```
I was expecting this to work whatever the initial environment is, as long as the `_install` target was already built.

**Comment by lukemaurer** [comment]
> In particular, I usually run the `opam custom-install` command in a different directory:
> 
> ```
> cd ~/opam_tests
> opam switch create . --empty
> opam custom-install ocaml-variants.4.12.0+flambda2 -- make -C path_to_flambda2/ install_for_opam
> opam reinstall --forget-pending
> opam install ocaml.4.12.0
> ```
> 
> I was expecting this to work whatever the initial environment is, as long as the `_install` target was already built.

The instructions currently specifically say to use the `flambda-backend` directory (and don't say to use `make -C`), so they should work that way. (Running `make _install` before creating the switch would also have worked, partly because it would have failed if I hadn't already run `eval $(opam env)`! So reordering the instructions to create the switch last would also help; currently they say to create the switch and _then_ run `make _install`.)

**Comment by lthls** [comment]
I put the switch creation instructions early because since you need to pass the destination prefix to `configure`, it felt better to have already created an empty switch at that point. But I think your suggestion to put all opam commands separately, after building `make _install`, make sense. I'll update the PR.

**Comment by lthls** [comment]
I've taken this opportunity to reorganise the section completely, cleaning up a few other outdated instructions on the way.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
