### PR TITLE
Removed RBP from `all_phys_regs`, `phys_reg` and `destroyed_at_oper`.

### PR DESCRIPTION
**Pull request by azewierzejew**
Returning `rbp` as a destroyed register when the code shouldn't even use `rbp` seems like a bad idea.

That wouldn't prevent misallocations in case of a bug but would make them much more rare and harder to find.

### CODE REVIEW

**Comment by mshinwell** [comment]
This needs a proper explanation please...

**Comment by mshinwell** [comment]
There were also some frame pointer related fixes upstream recently, I can't remember if they've been backported or not yet.

**Comment by Gbury** [comment]
what's the status on this one ?

**Comment by mshinwell** [comment]
@xclerc iiuc we discussed that this could be closed - if that's right, could you do so?

**Comment by gretay-js** [comment]
This is a good idea that should be submitted upstream first. In the meantime, #1206 is an alternative  for irc.

**Pull request closed without merging**
