### PR TITLE
Delete unused continuations in to_cmm

### PR DESCRIPTION
**Pull request by Gbury**
This PR adds some simplification of unused continuations in to_cmm. This particularly happens in classic mode, which can generate continuations with zero uses for unused exn handlers, for isntance in the following program:

```ocaml
let f x = try () with _ -> x
```

With this PR we can now eliminate the unneeded exn handler, which simplifies the generated code quite a bit.

### CODE REVIEW

**Comment by mshinwell** [comment]
cc @xclerc

**Comment by Gbury** [comment]
Unfortunately, even with this PR, there are still some cases where we still have unused continuations, for instance:

```ocaml
let f x y =
  let foo b = if b then x else y in
  try () with _ -> if Sys.opaque_identity true then foo true else foo false
```

**Comment by mshinwell** [comment]
@xclerc This is going to be harder than expected, could you consider again whether this can be handled in Cfg?

**Comment by xclerc** [comment]
Sorry for the delayed reply. We can probably either
work around the problem in the CFG, or even try and
reconstruct the info to be able to delete the dead
handlers.

There is something that would make it trivial on the
CFG side and may not be difficult to compute in the
middle-end side: would it be easy to annotate
`Cmm.Pop` with the label of its corresponding
`Cmm.Pushtrap`?

**Comment by Gbury** [comment]
This is not needed anymore since #1383 has been merged.

**Pull request closed without merging**
