### PR TITLE
Ltail for lambda and use in dissect_letrec

### PR DESCRIPTION
**Pull request by chambart**
This is used to avoid giving a return layout in dissect_letrec.

@stedolan Said that he had a patch implementing Ltail. I would be happy to use his instead.

### CODE REVIEW

**Comment by lpw25** [comment]
This is implemented as part of https://github.com/ocaml-flambda/ocaml-jst/pull/51 which is about to be merged

**Comment by chambart** [comment]
Thanks, I'll wait for this

**Comment by mshinwell** [comment]
It's now called `Lexclave` not `Ltail`; see #1334

**Comment by chambart** [comment]
This is now based on exclave.
I don't know really what an exclave in the middle of a letrec would mean (when to allocate, what is the lifetime...). Is it really allowed ?
So I kept the fatal error on exclave in dissect letrec.

**Review by mshinwell — APPROVED** [review]

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
