### PR TITLE
Adjust use of kinds during CPS conversion

### PR DESCRIPTION
**Pull request by mshinwell**
Easy one first: add a missing kind propagation in the `Lstaticcatch` case.

Harder: switch to a code fragment / idea suggested independently by @lpw25 and @chambart , which will produce fewer `Let_cont`s, which is good.  This new code will cause the value kind/subkind information on `Llet` to be dropped in certain cases (note: not the `Lprim` case).  However it seems like this information shouldn't be needed anyway and @lpw25 would like to stop providing it in Lambda, since it's expensive to compute.  If it's essential for a particular primitive we can add it to that primitive.  In general, though, we should have the kind/subkind information from the "inputs": function parameters, results of function applications, etc -- up to the bound in `Typeopt.value_kind` at least.

### CODE REVIEW

**Comment by lthls** [comment]
@chambart noted that we are going to lose potentially useful kind information.
For example, `let x = debug (); r.f in ...` will not have any subkind information on `x`. If we have precise information on `r` we could recover the information from that, but we've made the Lambda value kinds shallow on purpose so it's very easy to find actual examples where the kind is lost, and that can prevent us from doing other optimisations (typically unboxing).

**Comment by mshinwell** [comment]
If you think it's going to be easy to find useful examples where the kind is lost, maybe we shouldn't do the second change.

**Comment by lthls** [comment]
I agree that the kinds on join points make this change much less risky.
But I think we still lose optimisations:
```
let get a i = Array.get a i in
let x =
  let _ = ... in
  Sys.opaque_identity [| 0 |]
in
get x 0
```
I believe that the array access will not be specialised anymore, because we will have lost the kind of `x`.

**Comment by lpw25** [comment]
That kind of example will presumably also lose it's optimization if it was changed to:
```ocaml
let get a i = Array.get a i in
let _ = ... in
get (Sys.opaque_identity [| 0 |]) 0
```
So I don't think that putting value kinds on `let`'s is the correct solution (if a solution is really needed here).

**Comment by lthls** [comment]
I agree that the current state isn't optimal. But I don't see the point in losing information on purpose, for no benefit, before we've found a better way to propagate information. Typically, value kinds on primitives would solve our problem, but I'm not sure it's less expensive than value kinds on let-bindings.

**Comment by lpw25** [comment]
I think that we shouldn't do a potentially expensive operation on every let binding without some compelling evidence that it makes actual programs better. Doing it on primitives would be an improvement semantically, but still seems like a waste of compile time. IIUC there isn't even any sharing of these value kind representations, so we've got many copies of the same data all through our cmx files.

**Comment by lpw25** [comment]
Possible compromise approach: I think that having the information on join points is sufficient for all unboxing optimizations. I also think that the unboxing operations are the only ones that really benefit from having the deep value information. How about just the information needed for array specialization on the output of primitives and full value kinds only on the places we have now (minus let obviously)?

**Comment by mshinwell** [comment]
We could also do some measurements to see what the overhead actually is here.

**Comment by lthls** [comment]
So if I understand correctly, we can make a distinction between "useful and cheap" value kinds (boxed numbers, array kinds), that can be included at various points including primitives, and "expensive" value kinds (like records and variants) that will only be kept at join points. That would be fine with me.

**Comment by mshinwell** [comment]
We're adding "kinds on lets" to our general todo list, but going to close this specific PR for now.

**Pull request closed without merging**
