### PR TITLE
Default layout variables in gadt constructors

### PR DESCRIPTION
**Pull request by goldfirere**
This is like #1423, but for GADT constructors. Caught while working on my layout annotations patch (#1417), which will print undefaulted variables.

Request review from @ccasin and @lpw25 (because this also affects modes).

### CODE REVIEW

**Comment by goldfirere** [comment]
Without the change in the code, the test case failed in the safety check. But this really should be a type error. The use of separate modules there was to observe the fact that a serialized layout variable can be instantiated differently in any importing module -- very dangerous!

**Comment by ccasin** [comment]
Agree that we need something like this.  I'm wondering if it would be better to do it in `Typedecl.default_decl_layout`, where we default other sort variables in decls, to keep it all in one place.  See the `CR layouts v2` I left there about the need for more defaulting in cases like this.

**Comment by ccasin** [comment]
> Agree that we need something like this. I'm wondering if it would be better to do it in `Typedecl.default_decl_layout`, where we default other sort variables in decls, to keep it all in one place. See the `CR layouts v2` I left there about the need for more defaulting in cases like this.

Or maybe the observation is actually that we're kind of duplicating work in `closed_type_decl` and `default_decl_layouts` and we should just eliminate one of them?

**Comment by lpw25** [comment]
I agree that you can probably just have one of `closed_type_decl` and `default_decl_layouts`. Certainly the logic in the PR belongs with the logic from `default_decl_layouts`.

I'd vote against having a list of all sort variables in general. Certainly for modes it would give the wrong behaviour: you don't want to default all mode variables, you want to default as few mode variables as possible to free up the middle-end to choose the best mode for performance. It's not entirely clear whether the same is true for sorts: in principle letting the middle-end choose `void` will let it produce more efficient code, but that more efficient code is probably dead in this case. Still I think it makes more sense to use the same approach.

I'm also think it would be slower: I suspect we make a lot of sort variables and most of them won't be in places that require defaulting. Since we need to traverse those places to look for mode variables and ungeneralized type variables we aren't really going to save anything.

I'm more open to the idea of keeping a list of the sort variables you make whilst translating type expressions, since IIUC those always need to be defaulted, and for some of those you are currently doing an additional traversal not needed for mode variables or ungeneralized type variables. Also any sorts in those that aren't part of the resulting type can't affect compilation at all, so it doesn't matter if you somehow default some variables that didn't need to be defaulted. This assumes that all the sort variables that might end up in the resulting type come from somewhere in `typetexp.ml` -- if they can also get created during e.g. unification then it's probably not worth the effort to collect them all.

**Comment by goldfirere** [comment]
OK. Chris made some of the same arguments on Jira. If we observe that defaulting in type expressions becomes a bottleneck, it might be worth revisiting the list idea (used locally only within type expressions), but I agree to abandon it for now.

I will rewrite this patch to work in `default_decl_layouts`, which I had missed.

There is still the larger question of the duplication between `default_decl_layouts` and `closed_type_decl` (which called `remove_mode_and_layout_variables`).

Actually, in thinking about it, I wonder whether I can just delete `default_decl_layouts` entirely: the existing `closed_type_decl` should completely cover the same work. I'll experiment and see what I come up with.

**Comment by goldfirere** [comment]
This is ready for final review. The CI failure was a transient failure, fixed in #1429.

**Review by ccasin — APPROVED** [review]
Looks good.  I think it's fine for mode variables too - the same reason Leo gave in the other case applies.

It does change when defaulting happens relative to checking constraints, but I played around briefly and failed to construct an example where that was observable.  Even if one existed, it could be worked around with annotations.

**Pull request merged**
