### PR TITLE
Local immutable arrays

### PR DESCRIPTION
**Pull request by antalsz**
This is the migration of ocaml-flambda/ocaml-jst#156 to flambda-backend; most of the review should therefore already be done.

### CODE REVIEW

**Comment by goldfirere** [comment]
Let me know when this is ready for review (knowing that review is already under-way in the source PR); happy to look at the front-end and library bits.

**Comment by antalsz** [comment]
@mshinwell I'm trying to figure out if it makes sense to pull the `array_{ref,set}_kind` types forward into flambda2 as well.  I was trying to since I thought it did, but there's a lot of extra machinery around them in flambda2 that makes it less obvious to me.  Thoughts?

**Comment by antalsz** [comment]
@goldfirere, this is ready for review again; you should've already seen all the changes through [87356f3](https://github.com/ocaml-flambda/flambda-backend/pull/1420/commits/87356f3a615126e681adc3d7d21ae7acf694715e), so there may not be a ton for you to go over

**Comment by antalsz** [comment]
Status of the commits:
* 43268695f3bd9656a25824fc97d13aab62347b0a is all the stuff from the old PR (ocaml-flambda/ocaml-jst#156)
* c3a3849757145f007e3097aa0a4dfbeda198c6c6 applies the middle- and back-end stuff from the old PR to the top-level directories
* d95bb8b8b7c0eaab43b9fcb610dac71f954a0304 responds to a bit of review
* 2bdaf061145a575790cc06811ed09c53c6fb2757 is broken code that represents the start of me attempting to port stuff to flambda2
* 14482dfedb1fb4e44feac624b288b276b126a3fd is @mshinwell completing the port of local immutable arrays to flambda2

**Review by Gbury — APPROVED** [review]
The flambda2 part looks good.

**Comment by goldfirere** [comment]
@Gbury Thanks. Just so we make sure the whole patch is reviewed, what parts did you look at?

**Comment by Gbury** [comment]
> @Gbury Thanks. Just so we make sure the whole patch is reviewed, what parts did you look at?

I looked at everything in the `middle_end/flambda2` directory, and also had a quick look at the changes in the `backend` directory.

**Comment by antalsz** [comment]
@mshinwell I believe this completes review – @goldfirere has reviewed the front-end stuff (back on ocaml-jst), you've reviewed the middle- and back-end stuff except for what you wrote, and @Gbury has reviewed the middle-end stuff you wrote.  There was [one outstanding question on the old PR](https://github.com/ocaml-flambda/ocaml-jst/pull/156#discussion_r1226910668), and I'll rebase this to fix the `ocaml/boot` conflicts, but then it looks like we're ready to merge!

**Review by goldfirere — APPROVED** [review]
Approving based on review of the ocaml-jst version of this patch.

**Comment by antalsz** [comment]
@mshinwell added

**Review by mshinwell — APPROVED** [review]
One comment: we've discussed maybe adding extra libraries to the compiler distribution so we don't need to change the stdlib so much.  If we did this for immutable arrays, maybe we could then use the literal syntax, and also comprehensions too?  It's a bit disappointing that we have so many uses of `unsafe_of_array`, in particular.

**Comment by mshinwell** [comment]
This has had sufficient review, merging.

**Pull request merged**
