### PR TITLE
Refactor comparison

### PR DESCRIPTION
**Pull request by smuenzel**
Refactor comparison in order to consolidate all comparison related types in the backend in the same file.
This is needed for adding cmov (see https://github.com/ocaml-flambda/flambda-backend/pull/172)
This is based on a patch by pdenys (https://github.com/ocaml/ocaml/issues/6224)

### CODE REVIEW

**Comment by mshinwell** [comment]
Is the only reason for this change so that the amd64 specific operation type can refer to comparisons?  If so I wonder if we should have a conditional move expression/operation in `Cmm` itself.  I think this might produce a much smaller patch.

**Comment by smuenzel** [comment]
Yeah, that's the original motivation. It's a bit cleaner as well.

Adding it to cmm would also work, but even though the patch might be smaller, it would need to be more than just the code motion we have here: we'd need to implement cmov on all architectures, which would also mean that review would be more complicated (and someone will have to look up how it works for N architectures....)

**Comment by mshinwell** [comment]
I don't think that's the case: it could expand to the existing code sequence if the architectures don't implement it.

**Comment by gretay-js** [comment]
In the comments about the original PR upstream, years ago, people were interested in general conditional instructions for ARM. We could add a condition to CMM operations in general, with initial supported for particular operations on amd64 backend only (i.e., selectgen never generates a condition), and then gradually it can be added to more targets using  `Proc.operation_supported`.

**Comment by lpw25** [comment]
It's not clear to me what a conditional move operation is in cmm. Conditional move seems like it only makes sense on mutable variables and I think we intend to remove those from cmm.

I guess you could add a restricted version of `if`, but that already has a representation that seems pretty easy to detect in instruction selection, so it's not that clear to me what you gain.

**Comment by smuenzel** [comment]
So I guess this means we should keep proceeding with this patch? And if we want to have cmov for other architectures, we can share the selection function, so that we don't have to maintain two versions

**Comment by gretay-js** [comment]
> It's not clear to me what a conditional move operation is in cmm. Conditional move seems like it only makes sense on mutable variables and I think we intend to remove those from cmm.

I was referring to conditional execution of other instructions, not just mov, on aarch32 (which probably what the old comment was about). It's less relevant for aarch64.

**Comment by lpw25** [comment]
Maybe, although my preference would probably be to do something slightly different. I'd add a separate test type to the amd64 arch file and then write an injection from the generic test type to the architecture-specific test type in the emit file and use that in any places where you want to share code between the two types. I see no reason that the tests available on a specific architecture should match one-to-one with the generic set of tests available on all architectures, so I'd prefer not to force them to be the same by using the same type. In general, I have a preference for not sharing types between different IRs -- half the time it turns out that you actually want the types to be different later and it is painful to split the uses back out to separate types.

Another option would be to have cmov not be architecture specific -- but I'd worry that might degrade the quality of the produced code on architectures without it.

**Comment by mshinwell** [comment]
What Leo just wrote about having two sets of types was in fact something I was thinking about this morning.  I think that's a promising route to take.  It is certainly also the case in general that sharing of types between IRs should be avoided.

**Comment by mshinwell** [comment]
(sorry accidentally hit "close")

**Comment by smuenzel** [comment]
I think that means we effectively have to duplicate the entire set of types in [Comparison] in [Arch] (and we can't seperate it into a separate file either). And we need to write no-op conversion functions.
(Note that we do want to preserve the sharing of conditions between the tests in Cmm and the tests in the architecture specific cmov instructions).

If you are okay with the amount of extra code in arch, we can do this -- but I would postpone to a future refactoring, and leave the current one, which only moves code, but doesn't create new types.

**Pull request closed without merging**
