### PR TITLE
Fix a bug in slot_offsets when two separate sets of closures have a slot in common, but not all

### PR DESCRIPTION
**Pull request by Ekdohibs**
Extracted from #2642.

### CODE REVIEW

**Comment by Ekdohibs** [comment]
I'm not sure how to add a test, given it's something that isn't generated by the compiler as of now, and this can't be tested by flexpect either.

**Comment by Ekdohibs** [comment]
So, this fixes a bug, but there are other remaining. Indeed, we cannot put space between function slots in set of closures, as `Gc.compact` will scan that area (especially the arity). This will require more changes, the scope of which I am not sure about yet.

**Review by Gbury — APPROVED** [review]

**Comment by Gbury** [comment]
I'll look at the problem with consecutive slots as soon as I have the time.

**Comment by Ekdohibs** [comment]
The consecutive slots problem has been addressed in #2674.

**Pull request merged**
