### PR TITLE
Use Hashtbl for sparse matrix in build_graph

### PR DESCRIPTION
**Pull request by rleshchinskiy**
Set.add was actually showing up in the profile here and using a hash table reduces total allocations by about 5%.

### CODE REVIEW

**Comment by xclerc** [comment]
(cross-references: https://github.com/ocaml-flambda/flambda-backend/pull/553 https://github.com/ocaml-flambda/flambda-backend/pull/554)

**Comment by rleshchinskiy** [comment]
Heh, never mind then.

**Comment by xclerc** [comment]
I certainly did not imply it should be closed;
just wanted to make sure we would not miss
data points / discussion elements.

**Comment by rleshchinskiy** [comment]
But it's basically exactly the same as #553.

**Pull request closed without merging**
