### PR TITLE
Pack import fixes

### PR DESCRIPTION
**Pull request by lthls**
All opam packages using packs have been broken for a while (some of them since #871 has been merged). With this PR, we can finally compile most of the previously failing packages.
I think the code is still wrong in a few corner cases; I've left a CR though, and if someone knows how to fix them properly we should do it.

### CODE REVIEW

**Comment by mshinwell** [comment]
@lukemaurer could you please look at this?

**Comment by lthls** [comment]
It would be nice if we could get this merged before the week-end, so that we have updated opam health checks to look at on Monday.

**Comment by lukemaurer** [comment]
I think I made a mistake when I added the `~cmx_name` parameter. If the import info we want is exactly what is in the ui, then we don't actually want to take `comp_unit` and `cmx_name` as separate parameters to `get_unit_info` - it should just take `comp_unit` and then `let cmx_name = Compilation_unit.name comp_unit`. Then we don't need either change here to `get_unit_info` - we want to check that `ui.ui_unit` is exactly `comp_unit` and the import we want to add (with or without .cmx) is `comp_unit`.

I think the solution is to have `CU.which_cmx_file` return the full `CU.t` rather than just the name. I'll make a PR.

**Comment by lukemaurer** [comment]
#1069 should have this covered.

**Comment by mshinwell** [comment]
Superceded by #1069 which is now merged.

**Pull request closed without merging**
