### PR TITLE
Add AFL support for Flambda 2

### PR DESCRIPTION
**Pull request by mshinwell**
Seems like we just forgot about this.  I've tested this PR on a real fuzzing job and it seems to work ok.

### CODE REVIEW

**Review by Gbury — APPROVED** [review]
This looks correct, and should indeed fix the afl instrumentation. However, I wonder why the fact that afl instrumentation was broken with flambda2 was not detected by running the testsuite (which contains a test for afl instrumentation) ?

**Comment by mshinwell** [comment]
> This looks correct, and should indeed fix the afl instrumentation. However, I wonder why the fact that afl instrumentation was broken with flambda2 was not detected by running the testsuite (which contains a test for afl instrumentation) ?

See #1197

**Comment by mshinwell** [comment]
The `.ml` test file used for AFL only works with the reference output under flambda2 if the parts using `lazy` are commented out.  This is probably related to the different compilation strategy used for lazy values under flambda2 in `Translcore`.

**Comment by mshinwell** [comment]
I spoke to @stedolan about this and it seems like we need to investigate further what's causing the discrepancy with `lazy`.  It doesn't seem to be (directly) related to the different compilation path for `lazy` prior to the middle-end, as there is a different path used for AFL in all cases.

**Comment by mshinwell** [comment]
I'm going to merge the additions to the Flambda 2 code so this PR can be closed, and the support is there.  As far as I can see the AFL test cases pass on my macOS machine - it seems like there may be some problem with the `afl++` package used for the Linux CI.  We can investigate that separately.  I've had one other report of these tests being problematic on Linux too.

**Comment by ncik-roberts** [comment]
The lazy test is still failing on Linux (and I spent a few hours trying to debug it and fix it, not realizing that this conversation already happened). I'm fairly sure it's related to the GC. That is, running the GC shows up in the AFL instrumentation. I put more detail in this PR: https://github.com/ocaml-flambda/flambda-backend/pull/1789

Stephen doesn't want to merge #1789 because running the GC shouldn't affect instrumentation. But it's costly (in terms of developer time) and confusing to have a failing test run as part of the build. Does anyone have ideas as to why GC would show up in the AFL instrumentation?

**Comment by ncik-roberts** [comment]
The fix in ocaml/ocaml#1754 has `ap_inlined=Default_inlined;` on the call to `CamlinteralLazy.force` that's inserted when `-afl-instrument` is in force &mdash; I think that enables flambda2 to inline the definition (and thus cmm to instrument the code). Changing this to `Never_inlined` allows the test to pass. I'll open a PR for that.

**Pull request merged**
