### PR TITLE
Run the a CI job on both Ubuntu and macOS

### PR DESCRIPTION
**Pull request by xclerc**
Since macOS is the development platform for several of us,
such a job will allow us to spot issues sooner rather than later.

### CODE REVIEW

**Comment by xclerc** [comment]
The macOS job is currently failing -as expected- because of
the bits being reverted in https://github.com/ocaml-flambda/flambda-backend/pull/411. The job will be re-run when
https://github.com/ocaml-flambda/flambda-backend/pull/411 is merged.

**Comment by xclerc** [comment]
After rebasing, the job was failing because of an `ld` warning
(about a non-existent directory); this is fixed by https://github.com/ocaml-flambda/flambda-backend/pull/412/commits/077048b37bf9a2f8295a239132d34f3b90f112ed.
Will investigate the issue with the "lib-threads/beat" test.

**Comment by xclerc** [comment]
The "lib-threads/beat" test has two threads counting events
over a 3-second period. The first sees an event every 1/3 s
while the second one sees an event every 1/2 s. So, we
should in theory count respectively 9 and 6 events, and the
test accepts values respectively in 8..10 and 5..7. It does
currently fail returning 7 and 5.

**Comment by xclerc** [comment]
Another note: to be able to run all tests, one has to
install `gfortran` (e.g. by installing `gcc` through [brew](https://brew.sh))
and add the corresponding directory to `LIBRARY_PATH`.
For instance, I execute the following before launching
the test suite:
```
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/Cellar/gcc/11.2.0_3/lib/gcc/11"
```

**Comment by mshinwell** [comment]
@xclerc Can we try to get this ready for merge?  It sounds to me like that test is probably flaky.

**Comment by xclerc** [comment]
Do you have a preference between (i) widening the bounds,
and (ii) adding the test to `testsuite/flambda2-test-list`?

**Comment by mshinwell** [comment]
Not really, I will leave it to your judgement.

**Comment by xclerc** [comment]
I have a slight preference for the exclusion file, because it
ensures we will revisit the problem in due time. I will push
the change shortly.

**Comment by patricoferris** [comment]
Hi @mshinwell and @xclerc :))

I've been testing on macOS-arm64 locally to help eventually get macOS / arm64 CI support to the flambda-backend. This PR seems to get things to build locally for me and I pushed the same code to a [branch on my fork and CI seems to pass](https://github.com/patricoferris/flambda-backend/runs/4856213455?check_suite_focus=true), I'm wondering if the errors in the run on this PR were just some transient, macOS runner bug ?

It would seem that configuring with `flambda2` and `make -j8 ci` passes on macOS-arm64 too.

**Comment by xclerc** [comment]
Thanks for the feedback. I have been wondering whether the error
could actually be a timeout, but that was difficult to reconcile with
the log. I would like to retry, but the "Re-run all jobs" button is gone...

**Comment by xclerc** [comment]
Closed in favor of https://github.com/ocaml-flambda/flambda-backend/pull/488.

**Pull request closed without merging**
