### PR TITLE
Making the testsuite pass with runtime5

### PR DESCRIPTION
**Pull request by mshinwell**
This includes and is a continuation of #2027

### CODE REVIEW

**Comment by TheNumbat** [comment]
May need to rebase/squash now to get a proper diff from #2027

**Comment by mshinwell** [comment]
Current failing tests with `--enable-runtime5` are the following, plus the `tool-debugger` ones that are temporarily disabled (they seem to cause intermittent hangs):
```
List of failed tests:
    tests/lib-dynlink-native/'main.ml' with 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.2.2.1.1.1.1.1.1.1.1.1.1 (run) 
    tests/backtrace/'names.ml' with 2 (bytecode) 
    tests/tool-toplevel/'any.ml' with 1 (toplevel.opt) 
    tests/backtrace/'backtrace_c_exn.ml' with 2 (native) 
    tests/backtrace/'names.ml' with 1 (native) 
    tests/lib-dynlink-private/'test.ml' with 1.2.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1 (run) 
    tests/backtrace/'lazy.ml' with 2.1 (native) 
    tests/instrumented-runtime/'main.ml' with 1.1 (native) Fatal error
    tests/lib-dynlink-pr9209/'dyn.ml' with 1.1.1.1.1.1.1 (run) Process 58826 got signal 11(Segmentation fault
    tests/lib-dynlink-bytecode/'main.ml' with 1.1.1.1.1.1.1.1.1 (run) Process 58158 got signal 11(Segmentation fault
    tests/backtrace/'backtrace_dynlink.ml' with 1.1.1.3.1.1 (check-program-output) 
```
plus the following which are because of missing forward ports from 4.x:
```
    tests/async-exns/'async_exns_1.ml' with 1 (native) 
    tests/async-exns/'async_exns_1.ml' with 2 (bytecode) 
    tests/tool-ocaml/'t360-stacks-2.ml' with 1.1 (ocaml)   (this uses async exns)
    tests/lib-obj/'get_header.ml' with 2 (bytecode) 
    tests/lib-systhreads/'swapgil.ml' with 1.1.1 (native) 
```

**Comment by mshinwell** [comment]
Updated first list from above:
```
    tests/lib-dynlink-native/'main.ml' with 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.2.2.1.1.1.1.1.1.1.1.1.1 (run) 
    tests/tool-toplevel/'any.ml' with 1 (toplevel.opt) 
    tests/lib-dynlink-private/'test.ml' with 1.2.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1 (run) 
    tests/lib-dynlink-bytecode/'main.ml' with 1.1.1.1.1.1.1.1.1 (run) Process 93932 got signal 11(Segmentation fault
    tests/lib-dynlink-pr9209/'dyn.ml' with 1.1.1.1.1.1.1 (run) Process 94677 got signal 11(Segmentation fault
    tests/instrumented-runtime/'main.ml' with 1.1 (native) Fatal error
    tests/backtrace/'backtrace_dynlink.ml' with 1.1.1.3.1.1 (check-program-output) 
```

**Comment by mshinwell** [comment]
Updated status:
```
    tests/lib-dynlink-native/'main.ml' with 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.2.2.1.1.1.1.1.1.1.1.1.1 (run)
    tests/lib-dynlink-private/'test.ml' with 1.2.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1 (run)
    tests/backtrace/'backtrace_dynlink.ml' with 1.1.1.3.1.1 (check-program-output) 
```

**Comment by mshinwell** [comment]
The only failures are now the following, which are expected.
```
List of failed tests:
    tests/async-exns/'async_exns_1.ml' with 1 (native) 
    tests/lib-systhreads/'swapgil.ml' with 1.1.1 (native) 
    tests/async-exns/'async_exns_1.ml' with 2 (bytecode) 
    tests/lib-obj/'get_header.ml' with 2 (bytecode) 
    tests/tool-ocaml/'t360-stacks-2.ml' with 1.1 (ocaml) 
```

**Comment by mshinwell** [comment]
Moved to the `runtime5-features` branch on `ocaml-flambda`.

**Pull request merged**
