### PR TITLE
Add attributes effects and coeffects

### PR DESCRIPTION
**Pull request by gretay-js**
Second part of  #11

### CODE REVIEW

**Comment by gretay-js** [comment]
I removed XCRs and rebased this PR. It is ready for review @lpw25 @antalsz.

**Comment by gretay-js** [comment]
Following the discussion in https://github.com/ocaml-flambda/flambda-backend/pull/14#pullrequestreview-753736532, I updated `backend/cmm_helpers.ml` to set `Has_coeffects` on external calls without `[@@noalloc]` and changed `asmcomp/cmm_helpers.ml` to always set conservative effects and coeffects.

**Review by xclerc — COMMENTED** [review]
The changes in "backend/cmm_helpers.ml" and
"ocaml/asmcomp/cmm_helpers.ml" are different.
Is it on purpose?
After reading the comment above, and the linked
discussion, I understand it is on purpose,

**Review by xclerc — APPROVED** [review]
(Not covering the typing bits.)

**Review by lpw25 — APPROVED** [review]
The typing changes are fine.

However, they will change the cmi file format, which means that we'll need to build a new merlin for a compiler containing this change. More generally we're going to have to be careful with making changes in typing in patch releases, to make sure that we don't get segfaults from merlin.

**Comment by mshinwell** [comment]
I've added a label "needs new merlin" which we can use for these issues.

**Comment by gretay-js** [comment]
> Shouldn't we alter the magic number for `cmi` files then?

I'm not sure... do we need to change it per PR or only per "release"?  They will all change with #275 anyway.

**Comment by xclerc** [comment]
I am not sure either, but I have been (recently) building code bases
with unreleased compilers and one certainly has to be cautious in
such situations.

**Comment by gretay-js** [comment]
I've rebased it and re-bootstrapped it but I haven't changed the magic number of cmi because it needs to get its new magic number after #275 is merged in, so it doesn't conflict with upstream magic numbers.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
