### PR TITLE
Flambda2 test list

### PR DESCRIPTION
**Pull request by xclerc**
This pull request changes the logic behind the file named
"testsuite/flambda2-test-list" in order to explicitly exclude
test directories rather than explicitly include such directories.
We expect its maintenance to be easier that way, and in
particular there is no risks to forget to add a newly-created
directory.

This pull request is possibly best reviewed commit-by-commit:
- commits from https://github.com/ocaml-flambda/flambda-backend/pull/494/commits/d32e5413fef4e2841c5bf22a0ca738210c46ebf1 to https://github.com/ocaml-flambda/flambda-backend/pull/494/commits/b1aac79eb15f1b55e82291117ce40b9caaa332c5 (both inclusive) are
  simply a minor clean-up, leaving the semantics of the file
  unchanged;
- commit https://github.com/ocaml-flambda/flambda-backend/pull/494/commits/1b89d070c28dd2546230a4658b27975bd8d9f607 changes the logic from opt-in to opt-out.

In order to double check that the last commit behaves as
expected, I diffed `_runtest/flambda2-test-list` before/after,
and got:
```
<   tests/comprehensions
---
>   tests/comprehension
109d108
<   tests/runtime-naked-pointers
110a110
>   tests/runtime-naked-pointers
```
which basically means that (i) the aforementioned clean-up
was not perfect and (ii) no tests were lost in the process.

### CODE REVIEW

**Comment by Gbury** [comment]
Maybe we should switch to using ocamlformat's features to enable/disable tests when running with flambda, rather than the current list of folders ?

**Comment by mshinwell** [comment]
In due course perhaps (I presume you mean dune not ocamlformat?).  One step at a time...

**Comment by Gbury** [comment]
> In due course perhaps (I presume you mean dune not ocamlformat?). One step at a time...

Oups, I meant ocamltest: the current list of test folders to run is used with the upstream testsuite, which uses ocamltest, where one can disable tests by adding a few lines in the test definition at the opt of the test file.

**Comment by xclerc** [comment]
I certainly agree that using `ocamltest` builtin mechanism
would be better in the long run, but our immediate concern
was to not ignore new test directories. Also, this switch from
opt-in to opt-out while still going through a centralized file
has one (unexpected) benefit: it is basically a TODO list of
the tests we need to fix...

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
