### PR TITLE
Add unboxed float array

### PR DESCRIPTION
**Pull request by alanechang**
Add support for arrays of unboxed floats.

Consists of:
- frontend changes to allow the type param of `array` to have non-value layout
- introduce new primitives for unboxed float array operations
- new `Float_u_array` and `Float_u_arrayLabels` modules in stdlib
- runtime functions for the new stdlib modules
- existing floatarray testsuite applied to unboxed float arrays

Things not yet working:
- flambda1 test segfaults
- upstream closure doesn't build
- `[||]` syntax doesn't work with unboxed floats (likely to be its own pr)

### CODE REVIEW

**Comment by mshinwell** [comment]
Don't worry about flambda1, I'll look at that tomorrow.  Does it work with flambda2?

**Comment by alanechang** [comment]
Yes, the tests are passing with flambda2.

**Comment by mshinwell** [comment]
@alanechang I've pushed some tentative fixes for flambda1

**Comment by alanechang** [comment]
@mshinwell I verified locally that the tests are still segfaulting when compiled with flambda1:

```
$ make test-one TEST=typing-layouts-float64/stdlib_float_u_array.ml
...
 ... testing 'stdlib_float_u_array.ml' with 1 (native) => Process 3781958 got signal 11(Segmentation fault), core dumped
Could not find core file.
failed (Running program /usr/local/home/alanechang/ocaml/flambda-backend-float-array-new/_runtest/testsuite/_ocamltest/tests/typing-layouts-float64/stdlib_float_u_array/ocamlopt.opt/stdlib_float_u_array.opt without any argument: command
/usr/local/home/alanechang/ocaml/flambda-backend-float-array-new/_runtest/testsuite/_ocamltest/tests/typing-layouts-float64/stdlib_float_u_array/ocamlopt.opt/stdlib_float_u_array.opt 
failed with exit code -11)
 ... testing 'stdlib_float_u_array.ml' with 2 (bytecode) => passed
 ... testing 'stdlib_float_u_array.ml' with 3 (native) => Process 3782035 got signal 11(Segmentation fault), core dumped
Could not find core file.
...

List of unexpected errors:
    /'stdlib_float_u_array.ml' with 1 (native) 
    /'stdlib_float_u_array.ml' with 3 (native) 

Summary:
    2 tests passed
    0 tests skipped
    0 tests failed
    0 tests not started (parent test skipped or failed)
    2 unexpected errors
    4 tests considered
#### Something failed. Exiting with error status.
```

**Comment by alanechang** [comment]
I looked a bit more into the crash:

```
0x000000000046c314 in caml_apply2 ()
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-225.el8_8.6.jane1.x86_64
(gdb) bt
#0  0x000000000046c314 in caml_apply2 ()
#1  0x00000000004cf472 in camlStdlib__Float_u_array__fold_right_525 () at ocaml/stdlib/float_u_array.ml:194
#2  0x000000000046f0c7 in camlStdlib_float_u_array__Test_1096 ()
#3  0x00000000004733f0 in camlStdlib_float_u_array__entry ()
#4  0x00000000004686cd in caml_program ()
#5  0x00000000004f08d5 in caml_start_program ()
#6  0x00000000004f1044 in caml_startup_common (argv=0x7fffffffdaf8, pooling=<optimized out>, pooling@entry=0)
    at startup_nat.c:160
#7  0x00000000004f10ab in caml_startup_exn (argv=<optimized out>) at startup_nat.c:175
#8  caml_startup (argv=<optimized out>) at startup_nat.c:175
#9  0x00000000004f10d5 in caml_main (argv=<optimized out>) at startup_nat.c:182
#10 0x000000000046859c in main (argc=<optimized out>, argv=<optimized out>) at main.c:37
```

```
(gdb) info registers 
rax            0x1                 1
rbx            0x715260            7426656
rcx            0x2e458fb           48519419
rdx            0x1f40              8000
rsi            0x715260            7426656
rdi            0x7cf               1999
rbp            0x7fffffffd818      0x7fffffffd818
rsp            0x7fffffffd8c0      0x7fffffffd8c0
r8             0x10                16
r9             0x7ffff7e6c008      140737352482824
r10            0x3e8               1000
r11            0x7ffff7e6c008      140737352482824
r12            0x7251d8            7492056
r13            0x4f0907            5179655
r14            0x72d2a0            7525024
r15            0x7ffff6bac270      140737332822640
rip            0x46c314            0x46c314 <caml_apply2+4>
eflags         0x10206             [ PF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```


It's happening on the call to `f` inside:

```ocaml
let fold_right f a x =
  let r = ref x in
  for i = length a - 1 downto 0 do
    r := f (unsafe_get a i) !r
  done;
  !r
```
> file stdlib/float_u_array.ml

Flambda 1:

```
(gdb) disassemble $rip
Dump of assembler code for function caml_apply2:
   0x000000000046c310 <+0>:	sub    rsp,0x18
=> 0x000000000046c314 <+4>:	mov    rsi,QWORD PTR [rdi+0x8]
   0x000000000046c318 <+8>:	sar    rsi,0x38
   0x000000000046c31c <+12>:	cmp    rsi,0x2
   0x000000000046c320 <+16>:	jne    0x46c32c <caml_apply2+28>
   0x000000000046c322 <+18>:	mov    rsi,QWORD PTR [rdi+0x10]
   0x000000000046c326 <+22>:	add    rsp,0x18
   0x000000000046c32a <+26>:	jmp    rsi
   0x000000000046c32c <+28>:	mov    QWORD PTR [rsp+0x8],rbx
   0x000000000046c331 <+33>:	mov    rbx,QWORD PTR [r14+0x90]
   0x000000000046c338 <+40>:	mov    QWORD PTR [rsp],rbx
   0x000000000046c33c <+44>:	mov    rsi,QWORD PTR [rdi]
   0x000000000046c33f <+47>:	mov    rbx,rdi
   0x000000000046c342 <+50>:	call   rsi
   0x000000000046c344 <+52>:	mov    rbx,rax
   0x000000000046c347 <+55>:	mov    rax,QWORD PTR [r14+0x90]
   0x000000000046c34e <+62>:	mov    rdi,QWORD PTR [rsp]
   0x000000000046c352 <+66>:	cmp    rdi,rax
   0x000000000046c355 <+69>:	jne    0x46c368 <caml_apply2+88>
   0x000000000046c357 <+71>:	mov    rdi,QWORD PTR [rbx]
   0x000000000046c35a <+74>:	mov    rax,QWORD PTR [rsp+0x8]
   0x000000000046c35f <+79>:	add    rsp,0x18
   0x000000000046c363 <+83>:	jmp    rdi
   0x000000000046c365 <+85>:	nop    DWORD PTR [rax]
   0x000000000046c368 <+88>:	mov    QWORD PTR [rsp],rdi
   0x000000000046c36c <+92>:	mov    rdi,QWORD PTR [rbx]
   0x000000000046c36f <+95>:	mov    rax,QWORD PTR [rsp+0x8]
   0x000000000046c374 <+100>:	call   rdi
   0x000000000046c376 <+102>:	mov    rbx,QWORD PTR [rsp]
   0x000000000046c37a <+106>:	mov    QWORD PTR [r14+0x90],rbx
   0x000000000046c381 <+113>:	add    rsp,0x18
   0x000000000046c385 <+117>:	ret    

(gdb) disassemble camlStdlib__Float_u_array__fold_right_525
Dump of assembler code for function camlStdlib__Float_u_array__fold_right_525:
   0x00000000004cf430 <+0>:	sub    rsp,0x18
   0x00000000004cf434 <+4>:	mov    rsi,rax
   0x00000000004cf437 <+7>:	mov    rax,rdi
   0x00000000004cf43a <+10>:	mov    rdi,QWORD PTR [rbx-0x8]
   0x00000000004cf43e <+14>:	shr    rdi,0x9
   0x00000000004cf442 <+18>:	or     rdi,0x1
   0x00000000004cf446 <+22>:	add    rdi,0xfffffffffffffffe
   0x00000000004cf44a <+26>:	cmp    rdi,0x1
   0x00000000004cf44e <+30>:	jl     0x4cf489 <camlStdlib__Float_u_array__fold_right_525+89>
   0x00000000004cf450 <+32>:	mov    QWORD PTR [rsp+0x10],rdi
   0x00000000004cf455 <+37>:	mov    QWORD PTR [rsp],rbx
   0x00000000004cf459 <+41>:	mov    QWORD PTR [rsp+0x8],rsi
   0x00000000004cf45e <+46>:	mov    rbx,QWORD PTR [rsp]
   0x00000000004cf462 <+50>:	movsd  xmm0,QWORD PTR [rbx+rdi*4-0x4]
   0x00000000004cf468 <+56>:	mov    rbx,QWORD PTR [rsp+0x8]
   0x00000000004cf46d <+61>:	call   0x46c310 <caml_apply2>
   0x00000000004cf472 <+66>:	mov    rdi,QWORD PTR [rsp+0x10]
   0x00000000004cf477 <+71>:	mov    rbx,rdi
   0x00000000004cf47a <+74>:	sub    rdi,0x2
   0x00000000004cf47e <+78>:	mov    QWORD PTR [rsp+0x10],rdi
   0x00000000004cf483 <+83>:	cmp    rbx,0x1
   0x00000000004cf487 <+87>:	jne    0x4cf45e <camlStdlib__Float_u_array__fold_right_525+46>
   0x00000000004cf489 <+89>:	add    rsp,0x18
   0x00000000004cf48d <+93>:	ret    
```

Flambda2 for comparison:

```
(gdb) disassemble caml_applyF_V
Dump of assembler code for function caml_applyF_V:
   0x00000000004531a0 <+0>:	sub    rsp,0x18
   0x00000000004531a4 <+4>:	mov    rdi,QWORD PTR [rbx+0x8]
   0x00000000004531a8 <+8>:	sar    rdi,0x38
   0x00000000004531ac <+12>:	cmp    rdi,0x2
   0x00000000004531b0 <+16>:	jne    0x4531bc <caml_applyF_V+28>
   0x00000000004531b2 <+18>:	mov    rdi,QWORD PTR [rbx+0x10]
   0x00000000004531b6 <+22>:	add    rsp,0x18
   0x00000000004531ba <+26>:	jmp    rdi
   0x00000000004531bc <+28>:	mov    QWORD PTR [rsp+0x8],rax
   0x00000000004531c1 <+33>:	mov    rax,QWORD PTR [r14+0x90]
   0x00000000004531c8 <+40>:	mov    QWORD PTR [rsp],rax
   0x00000000004531cc <+44>:	mov    rdi,QWORD PTR [rbx]
   0x00000000004531cf <+47>:	mov    rax,rbx
   0x00000000004531d2 <+50>:	call   rdi
   0x00000000004531d4 <+52>:	mov    rbx,rax
   0x00000000004531d7 <+55>:	mov    rax,QWORD PTR [r14+0x90]
   0x00000000004531de <+62>:	mov    rdi,QWORD PTR [rsp]
   0x00000000004531e2 <+66>:	cmp    rdi,rax
   0x00000000004531e5 <+69>:	jne    0x4531f8 <caml_applyF_V+88>
   0x00000000004531e7 <+71>:	mov    rdi,QWORD PTR [rbx]
   0x00000000004531ea <+74>:	mov    rax,QWORD PTR [rsp+0x8]
   0x00000000004531ef <+79>:	add    rsp,0x18
   0x00000000004531f3 <+83>:	jmp    rdi
   0x00000000004531f5 <+85>:	nop    DWORD PTR [rax]
   0x00000000004531f8 <+88>:	mov    QWORD PTR [rsp],rdi
   0x00000000004531fc <+92>:	mov    rdi,QWORD PTR [rbx]
   0x00000000004531ff <+95>:	mov    rax,QWORD PTR [rsp+0x8]
   0x0000000000453204 <+100>:	call   rdi
   0x0000000000453206 <+102>:	mov    rbx,QWORD PTR [rsp]
   0x000000000045320a <+106>:	mov    QWORD PTR [r14+0x90],rbx
   0x0000000000453211 <+113>:	add    rsp,0x18
   0x0000000000453215 <+117>:	ret    

(gdb) disassemble camlStdlib__Float_u_array__fold_right_14_51_code 
Dump of assembler code for function camlStdlib__Float_u_array__fold_right_14_51_code:
   0x00000000004c1210 <+0>:	sub    rsp,0x28
   0x00000000004c1214 <+4>:	mov    rsi,QWORD PTR [r14+0x90]
   0x00000000004c121b <+11>:	mov    QWORD PTR [rsp],rsi
   0x00000000004c121f <+15>:	mov    rsi,QWORD PTR [rbx-0x8]
   0x00000000004c1223 <+19>:	shr    rsi,0x9
   0x00000000004c1227 <+23>:	or     rsi,0x1
   0x00000000004c122b <+27>:	add    rsi,0xfffffffffffffffe
   0x00000000004c122f <+31>:	cmp    rsi,0x1
   0x00000000004c1233 <+35>:	jl     0x4c1274 <camlStdlib__Float_u_array__fold_right_14_51_code+100>
   0x00000000004c1235 <+37>:	mov    QWORD PTR [rsp+0x8],rbx
   0x00000000004c123a <+42>:	mov    QWORD PTR [rsp+0x10],rax
   0x00000000004c123f <+47>:	mov    rax,rdi
   0x00000000004c1242 <+50>:	mov    QWORD PTR [rsp+0x18],rsi
   0x00000000004c1247 <+55>:	mov    rbx,QWORD PTR [rsp+0x8]
   0x00000000004c124c <+60>:	movsd  xmm0,QWORD PTR [rbx+rsi*4-0x4]
   0x00000000004c1252 <+66>:	mov    rbx,QWORD PTR [rsp+0x10]
   0x00000000004c1257 <+71>:	call   0x4531a0 <caml_applyF_V>
   0x00000000004c125c <+76>:	mov    rsi,QWORD PTR [rsp+0x18]
   0x00000000004c1261 <+81>:	cmp    rsi,0x1
   0x00000000004c1265 <+85>:	je     0x4c1277 <camlStdlib__Float_u_array__fold_right_14_51_code+103>
   0x00000000004c1267 <+87>:	add    rsi,0xfffffffffffffffe
   0x00000000004c126b <+91>:	mov    QWORD PTR [rsp+0x18],rsi
   0x00000000004c1270 <+96>:	jmp    0x4c1247 <camlStdlib__Float_u_array__fold_right_14_51_code+55>
   0x00000000004c1272 <+98>:	xchg   ax,ax
   0x00000000004c1274 <+100>:	mov    rax,rdi
   0x00000000004c1277 <+103>:	mov    rbx,QWORD PTR [rsp]
   0x00000000004c127b <+107>:	mov    QWORD PTR [r14+0x90],rbx
   0x00000000004c1282 <+114>:	add    rsp,0x28
   0x00000000004c1286 <+118>:	ret   
```

The flambda 1 code calls `caml_apply2` and dereferences `rdi`  (cause of the crash) where as flambda2 calls `caml_applyF_V` and dereferences `rbx` in the same place.

@mshinwell Hope this information is helpful!

**Comment by mshinwell** [comment]
@Gbury do you think you could have a look at this flambda1 failure?

**Comment by Ekdohibs** [comment]
The failure is caused by an incorrect result_layout of the clambda primitives, this should fix it: https://github.com/Ekdohibs/flambda-backend/commit/4aaabd3738c00caa8097765e7ba79283d39b0006

**Comment by ccasin** [comment]
> The failure is caused by an incorrect result_layout of the clambda primitives, this should fix it: [Ekdohibs@4aaabd3](https://github.com/Ekdohibs/flambda-backend/commit/4aaabd3738c00caa8097765e7ba79283d39b0006)

An argument, perhaps, for preferring to add new primitives vs continuing to add/extend parameterization of existing ones.

**Comment by alanechang** [comment]
replaced by #2238

**Pull request closed without merging**
