### PR TITLE
Rationalise Flambda 2 directory structure

### PR DESCRIPTION
**Pull request by mshinwell**
I received some feedback about there being too many directories under `middle_end/flambda2/`, so as discussed, this rationalises them.

All of the test-related directories are now under `middle_end/flambda2/test/`, including the parser etc.

I'd like to investigate the split between `term_basics/` and `terms/`, but that can be done later.

### CODE REVIEW

**Review by lthls — APPROVED** [review]
I'm fine with this PR. The only (new) thing I find unsatisfying is the extra `test/tests` subdirectory. I think the new `test` directory could have been just the old `tests` one with the other things (parser, compare, and such) moved in.

**Comment by lukemaurer** [comment]
> I'm fine with this PR. The only (new) thing I find unsatisfying is the extra `test/tests` subdirectory. I think the new `test` directory could have been just the old `tests` one with the other things (parser, compare, and such) moved in.

I think it's good to have them separated out so that you know that _every_ subdirectory of `test/tests` has tests in it. This way you can just see what the tests are rather than having to think about whether `parser` could mean tests _of_ a parser.

(We could have the tests under `test` and the supporting libraries under `test/lib`. Then there's just one directory to skip and it's obvious.)

**Comment by lthls** [comment]
That makes sense. In that case, maybe just renaming the `test` directory to `testing` ? I still find `test/tests` annoying because it looks redundant. (Note that upstream has `testsuite/tests/`, which I also found annoying but makes sense for the same reasons.)

**Comment by Gbury** [comment]
I think that too much time and changes have occurred since this PR was opened, @mshinwell do you want to update it, or should we close this one and see later if we want to resurrect it ?

**Comment by mshinwell** [comment]
We will do something like this, but in a new PR

**Pull request closed without merging**
