### PR TITLE
Stop frame descriptor overflow

### PR DESCRIPTION
**Pull request by lukemaurer**
A port of https://github.com/ocaml-flambda/ocaml/commit/9db53f1b.

### CODE REVIEW

**Comment by mshinwell** [comment]
@stedolan We'd better discuss this.  There have been some out of memory problems on the JS tree which if I understand correctly can be fixed by using `-linscan`; however, that then causes frame table field overflow.  I'm not sure but I think some of the problem (maybe all) might be that the compilation of the Flambda 2 let-symbol construct causes all of the values required for the fields of a given symbol (e.g. a huge module block) to need to be live all at once, since the writes are not interspersed with the computations producing the field values.  I have had some initial thoughts as to how we might fix this, but would prefer to leave such a change in Flambda 2 until after the first production release.

What is really needed is a variable-length encoding here.

**Comment by mshinwell** [comment]
One other note is that this patch would need extending to cover the other architectures in the relevant assembly files.

**Comment by gretay-js** [comment]
This PR seems related to https://github.com/ocaml/ocaml/pull/10085, which gives a proper error message instead of chaning the encouding to use 32 instead of 16 bit.

**Comment by mshinwell** [comment]
#251 will hopefully remove the need for this, but needs testing on the JS tree.

**Comment by mshinwell** [comment]
#251 should remove the need for this.

**Pull request closed without merging**
