### PR TITLE
Fix cmm unboxing of local allocations

### PR DESCRIPTION
**Pull request by lpw25**
There was a small bug where the cmm unboxing code used a too aggresive check for if an allocation was a float or boxed integer, that meant it didn't treat any local allocations as floats or boxed integers. This meant code like:
```ocaml
let f x y =
  let z = x +. y in
  let t = x *. y in
  t = z
```
was allocating local floats for `z` and `t`.

### CODE REVIEW

**Comment by lpw25** [comment]
@TheNumbat it also looks like `is_unboxed_number_cmm` in `cmmgen.ml` is missing a case for `vec128`. I didn't fix that in this PR, but you should have a look and check that they are being correctly unboxed in closure mode.

**Comment by Gbury** [comment]
Note as @lthls said in his comment in #1491 that this PR makes it so that cmmgen unboxing can turn local allocations into heap allocations. That is safe, and when that unboxing "works" (i.e. actually removes the allocation altogether) it doesn't matter, but it's something that should be kept in mind for when the cmmgen unboxing heuristic does not work very well (and ends up duplicating allocations, in addition to erasing their local status).

**Comment by lpw25** [comment]
I don't think it does. Could you explain where the alleged heap allocations are coming from?

**Comment by lthls** [comment]
> I don't think it does. Could you explain where the alleged heap allocations are coming from?

https://github.com/ocaml-flambda/flambda-backend/blob/1c6432f00e4c18b447ceb2ea2666b5be9d926470/backend/cmmgen.ml#L483C6-L483C65

**Comment by lpw25** [comment]
That code produces local allocations if `bn` says the allocations are local.

**Comment by lthls** [comment]
Ah, I didn't see you had the mode in there. But then don't you risk moving local allocations out of their regions ?

**Comment by lpw25** [comment]
It can't move the allocation out of the region, since the value can't have moved out of the region. It might be possible for it to move inside of another region and cause an issue that way though. I suspect there isn't actually a way to cause this right now, but either that reasoning should be made precise or the code should be made more obviously robust to it.

**Comment by lpw25** [comment]
Yeah, it looks like this code was broken in two ways then:
```ocaml
let[@inline never] ignore_local (local_ y) = ()

let[@inline always] bar (local_ x) =
  let () = ignore_local (Some x) in
  x

let f x y = local_
  let z = x +. y in
  bar z
```
This will move the allocation of `z` into the region of `bar` and then leak it back out.

There's a pretty obvious fix: force the local unboxed bindings before going into a region. The only annoyance is making sure we only add bindings that we actually use. I'll have a go at fixing it that way.

**Comment by lpw25** [comment]
Ok, I've pushed some code to prevent the unboxing from moving underneath a region. It should now be safe.

**Comment by mshinwell** [comment]
@xclerc @lthls could you both please look at this again and approve?

**Review by xclerc — APPROVED** [review]

**Review by lthls — APPROVED** [review]

**Review by Gbury — APPROVED** [review]

**Comment by mshinwell** [comment]
@lpw25 I think this should probably be closed given we're all-flambda2 now

**Pull request closed without merging**
