### PR TITLE
Bypass linearize with -ocamlcfg flag

### PR DESCRIPTION
**Pull request by gretay-js**
This is a draft for now, waiting for the dust of 4.14 to settle.

The diff is a bit hard to read, best review commit by commit, or by inspecting the new pipeline directly, as most changes are just refactoring.

`test_cfgize` is no longer used. @xclerc do you want to keep it for testing anything in the IRC pipeline?

### CODE REVIEW

**Comment by xclerc** [comment]
I don't think the IRC pipeline would really
benefit of having this around, but there is
a (very remote) possibility we will use it
when testing the "layouts" feature.

So maybe keep it for now, simply with a
CR-someday to that effect.

**Comment by xclerc** [comment]
I likely misunderstood your question.
`test_cfgize` can go, but we should
keep the CFG equivalence code for
now.

**Comment by gretay-js** [comment]
> I likely misunderstood your question. `test_cfgize` can go, but we should keep the CFG equivalence code for now.

Do you  mean keeping  `Asmgen.recompute_liveness_on_cfg` ? `Cfg_equivalence` module itself is not removed in this PR.

**Comment by xclerc** [comment]
It sounds fine to remove `recompute_liveness_on_cfg`;
only `Cfg_equivalence` may be of use.

**Review by xclerc — APPROVED** [review]

**Pull request merged**
