### PR TITLE
Clean up algorithms

### PR DESCRIPTION
**Pull request by lukemaurer**
Removing several unimplemented functions from `Patricia_tree` and deleting the flambda2 copy of `Strongly_connected_components` (generalizing the upstream API as needed).

### CODE REVIEW

**Review by lthls — APPROVED** [review]
Sounds reasonable. Were there any differences in the actual code for the `Strongly_connected_components` modules (apart from the signature) ?

**Comment by lthls** [comment]
Answering my own question: the flambda2 version used a specialised version of `List.mem` on integers, and allows the input graph to have edges pointing outside the domain of the graph, ignoring those edges. The latter part is what is causing the CI failures, and needs to be fixed in some way (either ensure that all graphs are self-contained or relax the implementation like was done in the Flambda 2 version).
The `List.mem` specialisation could be added back too, it's quite safe.

**Comment by mshinwell** [comment]
@lukemaurer maybe add back the `List.mem` specialisation (into the original SCC module this time) and then we can merge this?

**Comment by lukemaurer** [comment]
> @lukemaurer maybe add back the `List.mem` specialisation (into the original SCC module this time) and then we can merge this?

Sure, done.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
