### PR TITLE
Fix parsecmm.mly in ocaml subdirectory

### PR DESCRIPTION
**Pull request by gretay-js**
Running `make tests` under `ocaml` directory is useful when making changes there.  It has been broken since 4.12 because we didn't have a separate copy of parsecmm.mly and asmgen tests to work with the changes in `backend` directory and our top-level `make runtests-upstream` target. 

This PR fixes parsecmm.mly so `make tests -C ocaml` can run, but there are still two tests failing:
```
List of failed tests:
    tests/lib-sys/'opaque.ml' with 1 (native) 
    tests/typing-objects/'Exemples.ml' with 1 (expect) 
```
The first will be fixed when we move to 4.13 (or whichever upstream release has `Iopaque` PR 9412). I don't know what's ailing the second one.

### CODE REVIEW

**Comment by mshinwell** [comment]
@gretay-js I'm a bit confused by this PR.  Should we not have our own copy of the Cmm parser?

**Comment by gretay-js** [comment]
> @gretay-js I'm a bit confused by this PR. Should we not have our own copy of the Cmm parser?

We have a copy of this parser for `backend`, but along the way we broke the copy under `ocaml/` which is what this PR proposes to fix.

**Comment by mshinwell** [comment]
Oh, I see.  This is fine then.

**Review by mshinwell — APPROVED** [review]

**Comment by gretay-js** [comment]
The copy for `backend`  is fine, by the way.

**Pull request merged**
