### PR TITLE
Proper Patricia tree map function

### PR DESCRIPTION
**Pull request by chambart**
I think that it is probably better to do it that way than  #369

### CODE REVIEW

**Comment by chambart** [comment]
Also replace uses of map that can benefit from map_sharing

**Review by Gbury — APPROVED** [review]
Seems indeed better than the other PR.
I have a quick question though: what are the cases where one would want to use `map` specifically, and not `map_sharing` ? Or, put another way, why not have the code of `map_sharing` for the `map` function ?

**Comment by lthls** [comment]
`map_sharing` has type `('a -> 'a) -> 'a t -> 'a t`, while `map` has type `('a -> 'b) -> 'a t -> 'b t`.
Whenever the type allows it, `map_sharing` is better, but that's not all the cases.
(We did discuss hacks with Pierre involving `Obj`...)

**Comment by lthls** [comment]
> [1]: Even if we had a `map` version that keeps sharing (by hacking with `Obj`), I'm not sure how frequent the sharing cases would actually be triggered, given that it's not very likely that for different arguments the values after mapping would have the same repr.

If you consider a call to map that gets instantiated to `('a list -> 'b list) -> 'a list t -> 'b list t`, you'll be able to share all the cases involving the empty list, for instance.
And some interesting things could happen if we combine all this with https://github.com/ocaml/ocaml/pull/8958...

**Review by lukemaurer — APPROVED** [review]

**Review by mshinwell — APPROVED** [review]

**Review by lthls — APPROVED** [review]

**Pull request merged**
